### ISSUE TITLE
怎么一直都是“请扫描二维码……”啊

### ISSUE THREAD

**Issue by suoba** [BBOOXX/QzonePhotoCrawler#2]
怎么一直都是“请扫描二维码……”啊
问题是在哪里扫描啊，自动的吗？

**Comment by BBOOXX** [comment]
文件夹根目录下 有个qrcode.png  用手机qq扫

**Comment by suoba** [comment]
根目录下没有那个图片。难道跟我的windows下pythong3环境有关？

**Comment by BBOOXX** [comment]
没有测试过 python3  你可以在 python2 里试一下

**Comment by JadenTseng** [comment]
扫描了这个二维码登录，但是遇到403错误
登录初始化……
获取二维码……
请扫描二维码……
请扫描二维码……
请扫描二维码……
请扫描二维码……
请扫描二维码……
请扫描二维码……
请扫描二维码……
请扫描二维码……
验证成功,登录中……
登录成功。
获取相册列表
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    login.getalbum()
  File "main.py", line 37, in getalbum
    album_request.raise_for_status()
  File "D:\03_install\Python35\lib\site-packages\requests\models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://tjalist.photo.qzone.qq.co
m/fcgi-bin/fcg_list_album_v3?
